### ISSUE TITLE
Unhandled Rejection at: Promise Promise

### ISSUE THREAD

**Issue by JerryAJ** [Srar/node-tap#20]
今天有空试了下您的node-sstap，出现了如下的错误：
**Unhandled Rejection at: Promise Promise {
  <rejected> Error: The specified module could not be found.
\\?\F:\_git\NodeTapGui\NodeTapGui\bin\x64\Debug\node_modules\cap\build\Release\cap.node
    at Object.Module._extensions..node (module.js:662:18)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\node-tap\node_modules\cap\lib\Cap.js:3:13)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10) } reason: Error: The specified module could not be found.
\\?\F:\_git\NodeTapGui\NodeTapGui\bin\x64\Debug\node_modules\cap\build\Release\cap.node
    at Object.Module._extensions..node (module.js:662:18)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\node-tap\node_modules\cap\lib\Cap.js:3:13)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)**

测试平台：
Window 10 x64 16299
nmap-7.70
tap-windows-9.21.2

命令格式：
.\sstap.exe --host ******.*** --port 10086 --passwd ***** --xtudp 20 --method aes-256-gcm --tcphost ******.*** --tcpport 10086 --tcppasswd ***** --tcpmethod aes-256-gcm 

另外小生顺便写了个GUI小程序，用来调用您的Node SSTap
![image](https://user-images.githubusercontent.com/10510947/39672933-eb9be27c-5165-11e8-8f88-d4ad7de1d79b.png)

**Comment by Srar** [comment]
这个错误应该是`npm install`时 编译`cap`模块失败导致的.

因为编译失败`cap.node`文件会不存在. 如果不需要多倍发包可以无视这个错误.

**Comment by Srar** [comment]
啊 等等这个好像是我提供的Release我看看我是不是忘记把`cap.node`放进去了

**Comment by JerryAJ** [comment]
是的，我下载的是您最新提交的Release

**Comment by Srar** [comment]
您在`cmd`或`powershell`中运行会出现这个错误吗？

**Comment by JerryAJ** [comment]
会的

**Comment by Srar** [comment]
方便使用`teamviewer`或别的远程工具来调试吗...因为光看日志的话我貌似想不出原因.

**Comment by JerryAJ** [comment]
请稍等

**Comment by JerryAJ** [comment]
899 373 491
m7jk96

**Comment by Srar** [comment]
好像我这`teamviewer `超过5分钟会强制断开, 不知道是否能加下tg或者qq?

**Comment by JerryAJ** [comment]
qq: 1779611965
tg 不常用...

**Comment by Srar** [comment]
已经发出申请了
