### ISSUE TITLE
运行报错,启动没有效果

### ISSUE THREAD

**Issue by CodFrm** [Srar/node-tap#21]
node 版本
v8.9.4

执行命令
```
sstap.exe --host xxx --port xxx --passwd xxx --xtudp 20 --method aes-256-cfb --tcphost xxx --tcpport xxx --tcppasswd xxxx --tcpmethod aes-256-cfb
```

运行结果
```
netsh interface ipv4 set interface 13 metric=1
netsh interface ipv6 set interface 13 metric=1
netsh interface ipv4 set dnsservers 13 static 8.8.8.8 primary
netsh interface ip set address name=13 static 10.198.75.60 255.255.255.0 10.198.75.61
route delete 0.0.0.0 10.198.75.61
route delete 8.8.8.8
route add 10.1.1.11 mask 255.255.255.255 192.168.1.1 metric 1
route add 47.75.34.237 mask 255.255.255.255 192.168.1.1 metric 1
route add 47.75.34.237 mask 255.255.255.255 192.168.1.1 metric 1
create ip forward entry result: ERROR code: 5
XTUdp: 20
Default ip of adapter: 192.168.1.10
Default gateway of adapter: 192.168.1.1
Unhandled Rejection at: Promise Promise {
  <rejected> Error: ��һ�ַ���Ȩ�޲�����ķ�ʽ����һ�������׽��ֵĳ��ԡ�

    at new Socket (C:\snapshot\node-tap\node_modules\raw-socket\index.js:47:14)
    at Object.exports.createSocket (C:\snapshot\node-tap\node_modules\raw-socket\index.js:202:9)
    at registerXTUdp (C:\snapshot\node-tap\output\filters\TimesUDP.js:0:0)
    at Object.<anonymous> (C:\snapshot\node-tap\output\filters\TimesUDP.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17) } reason: Error: ��һ�ַ���Ȩ�޲�����ķ�ʽ����һ�������׽��ֵĳ��ԡ�

    at new Socket (C:\snapshot\node-tap\node_modules\raw-socket\index.js:47:14)
    at Object.exports.createSocket (C:\snapshot\node-tap\node_modules\raw-socket\index.js:202:9)
    at registerXTUdp (C:\snapshot\node-tap\output\filters\TimesUDP.js:0:0)
    at Object.<anonymous> (C:\snapshot\node-tap\output\filters\TimesUDP.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
```

不知道大佬这个是什么原因,我下的 1.1 的版本

**Comment by Srar** [comment]
```
ERROR_ACCESS_DENIED
5 (0x5)
Access is denied.
```
使用管理员权限运行

**Comment by CodFrm** [comment]
ha....可以了,我写了一个bat文件,直接打开运行,忘记了管理员权限,抱歉
