### ISSUE TITLE
ipv6地址不能解析

### ISSUE THREAD

**Issue by Ttt749** [Srar/node-tap#64]
.\sstap.exe --host 2001:da8:8000:1:202:120:2:101 --port 443 --passwd sr011530 --xtudp 20 --method aes-256-cfb --disablev6 false
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: queryA ENOTFOUND 2001:da8:8000:1:202:120:2:101
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:238:19)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'queryA',
  hostname: '2001:da8:8000:1:202:120:2:101' } } reason: { Error: queryA ENOTFOUND 2001:da8:8000:1:202:120:2:101
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:238:19)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'queryA',
  hostname: '2001:da8:8000:1:202:120:2:101' }

还是无法使用ipv6吗

**Comment by Srar** [comment]
是的 还不支持IPv6

**Comment by Ttt749** [comment]
好的，谢谢！希望可以实现一下
