### ISSUE TITLE
win10下使用手机USB共享网络导致的报错

### ISSUE THREAD

**Issue by SmRiley** [Srar/node-tap#65]
发现错误后，开始挺奇怪的，以为是系统的关系（因为之前成功运行过），排除很多项后，考虑到会不会是因为用手机USB共享网络链接的关系，尝试电脑直接链接校园WiFi后发现没有问题（排除校园WiFi的问题）.后用手机移动网络开热点也没有发现问题，基本判断为手机USB共享网络给电脑导致的问题（问题较为小众）。
报错信息如下

```
Route deletion failed. Code: 1168. Route: 10.198.75.255/255.255.255.255
IPv6 has been disabled.
netsh interface ipv4 set interface 22 metric=1 
netsh interface ipv6 set interface 22 metric=1 
netsh interface ipv4 set dnsservers 22 static 8.8.8.8 primary 
netsh interface ip set address name=22 static 10.198.75.60 255.255.255.0 10.198.75.61 
route delete 0.0.0.0 10.198.75.61 
route delete 8.8.8.8 
route add ********* mask 255.255.255.255 192.168.42.129 metric 1 
route add ********* mask 255.255.255.255 192.168.42.129 metric 1 
netsh int ipv6 delete route ::/0 interface=22 nexthop=fd05:5dd5:b158:0b23:0000:0000:0000:0004 
netsh int ipv6 delete address interface=22 address=fd05:5dd5:b158:0b23:0000:0000:0000:0005 
XTUdp: 20
Default ip of adapter: 192.168.42.227
Default gateway of adapter: 192.168.42.129
Unhandled Rejection at: Promise Promise {
<rejected> TypeError: device must be a string
at registerXTUdp (C:\snapshot\node-tap\output\filters\TimesUDP.js:0:0)
at Object.<anonymous> (C:\snapshot\node-tap\output\filters\TimesUDP.js:0:0)
at Module._compile (pkg/prelude/bootstrap.js:1243:22)
at Object.Module._extensions..js (module.js:644:10)
at Module.load (module.js:552:32)
at tryModuleLoad (module.js:495:12)
at Function.Module._load (module.js:487:3)
at Module.require (module.js:577:17)
at Module.require (pkg/prelude/bootstrap.js:1153:31)
at require (internal/module.js:11:18) } reason: TypeError: device must be a string
at registerXTUdp (C:\snapshot\node-tap\output\filters\TimesUDP.js:0:0)
at Object.<anonymous> (C:\snapshot\node-tap\output\filters\TimesUDP.js:0:0)
at Module._compile (pkg/prelude/bootstrap.js:1243:22)
at Object.Module._extensions..js (module.js:644:10)
at Module.load (module.js:552:32)
at tryModuleLoad (module.js:495:12)
at Function.Module._load (module.js:487:3)
at Module.require (module.js:577:17)
at Module.require (pkg/prelude/bootstrap.js:1153:31)
at require (internal/module.js:11:18)
```

**Comment by Srar** [comment]
看日志应该是多倍UDP发包选择网卡时候出的问题. 

可以先尝试将多倍发包禁用(xtudp参数设置成1) 看看是否可以正常使用.

**Comment by SmRiley** [comment]
多倍发包禁用后问题暂时解决，毕竟问题比较小众.

**Comment by Srar** [comment]
我后续会尝试类似场景看看是否能重现

**Comment by SmRiley** [comment]
从台式机转到笔记本上重试后问题是能够复现的.感谢你的回复.

**Comment by Srar** [comment]
查了下相关的问题:
https://stackoverflow.com/questions/40647812/wireshark-doesnt-show-interface-when-ndis-miniport-driver-installed

接上USB共享网络后重启下pcap服务再开启就没问题了

**Comment by SmRiley** [comment]
感谢您的回复Thanks♪(･ω･)ﾉ
